# create a playbook to provision nginx web server in the web-node

# Yaml file starts with ---
---

# where do you want to install or run this playbook
- hosts: web

# find the facts (show logs) - optional
  gather_facts: yes

# provide admin access to playbook - use sudo
  become: true

# provide the actual instructions - install nginx
  tasks:
  - name: provision/install/configure nginx
    apt: pkg=nginx state=present

# ensure nginx is running - enabled

